// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"greet/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

//
// todo x: 注册一个路由
//
func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/greet/from/:name",
				//
				// todo x: 业务 handler 方法
				//
				Handler: greetHandler(serverCtx),
			},
		},
	)
}
